### ISSUE TITLE
Strange behavior on the bitrate

### ISSUE THREAD

**Issue by robustini** [funneld/djifpv_boost_bitrate#1]
I noticed that with this plugin installed if the video link drops it instantly switches from 50 to 10 MBit, while without the plugin it gradually drops to steps, like 50/40/30/20/10.
This anomalous behavior does not give the user an estimate of the effective range, ie by dropping to the minimum instantly there is more risk of losing the video link if you do not perform a maneuver to approach the Goggles.

**Comment by funneld** [comment]
Never noticed this issue.

What type of airunit do you have? What packages installed? What power level? On 25mW I would expect something like that. 

Maybe the channel you selected had a lot of noise at that time?

**Comment by robustini** [comment]
> Never noticed this issue.
> 
> What type of airunit do you have? What packages installed? What power level? On 25mW I would expect something like that.
> 
> Maybe the channel you selected had a lot of noise at that time?

In all honesty the system was armed and I noticed that thing.
Today I flew again and the bitrate was almost always constant at 19 MBit, when normally before the root and your plugin it varied from 50 to 20.
Tested at 1200 mW.

**Comment by robustini** [comment]
Before the root: delay:42ms bitrate:45.2Mbps
After the root: delay:34ms bitrate:19.8Mbps

**Comment by funneld** [comment]
Is it so hard to tell more details? At least what type of airunit do you have? You didn't answer all the questions I asked.

**Comment by funneld** [comment]
> 
If it doesn't work for you just don't use it.

**Comment by robustini** [comment]
Caddx Nebula Pro.
Free channel, just me in the remote countryside.

**Comment by funneld** [comment]
> Caddx Nebula Pro. Free channel, just me in the remote countryside.

Don't know what's going on. Isn't it advised to not run the Vista at 1200mW because it overheats too fast? The extra bitrate could make the unit heat even faster and cause issues. Did you also test on 700mW?

**Comment by robustini** [comment]
> > Caddx Nebula Pro. Free channel, just me in the remote countryside.
> 
> Don't know what's going on. Isn't it advised to not run the Vista at 1200mW because it overheats too fast? The extra bitrate could make the unit heat even faster and cause issues. Did you also test on 700mW?

This morning it was cool here, and during the flight the Vista cooled well, so I don't think there is an overheats problem, but I can try 700 mW.

**Comment by robustini** [comment]
My mistake, it works as it should, sorry!
19 Mbit it is active when we are in the public channel.
